// Original single-paragraph "description" copy for every product-page
// "included"/"add-on" item, kept verbatim from before the problem/fix +
// stat-badge redesign. Not imported anywhere — this is a content archive
// only, so the original prose is still around if it's useful later
// (e.g. long-form pages, blog posts, sales material).

export const archivedIncludedDescriptions: Record<string, Record<string, string>> = {
  seo: {
    "Technical Health Audit":
      "Slow, clunky pages get penalised by search engines — every extra 100ms of load time can cost roughly 1% in lost conversions, working directly against your SEO. We check your website's code and performance for exactly this: slow pages, broken elements, anything quietly working against you. We also take a handful of your live property listings and check whether the same issues are holding them back specifically. Everything is tested across every major device and browser, checking that your site actually functions properly everywhere a customer might land on it. Depending on what you'd prefer, we either implement every fix ourselves or hand you a clear, practical report so your own team can action it — either way, you also get our recommendations on how to keep it maintained going forward.",
    "Schema Implementation":
      "\"Schema\" is a hidden layer of code that clearly labels information on your website in a format search engines can read with total accuracy, rather than guessing. We apply this across your whole website first, so search engines can clearly understand what services you offer, where, and for whom. This directly boosts your SEO performance: pages with properly implemented schema see click-through rates increase by 20-30%, since it makes your pages eligible for rich results — the enhanced search listings that show extra detail like price and location right in the search results, making them stand out and get clicked more than a plain link. We then build a template specifically for your property listings — price, bedrooms, property type, location — so every property you list going forward is automatically labelled the same way, with no extra manual work required from you each time you publish. We'll also show you exactly how it's set up, so you know what to check if you ever change how listings are published.",
    "On-Page Audit":
      "Every page on your website is a chance to be found by the exact person searching for what you offer — but only if it's structured in a way search engines can understand, and laid out in a way a real person can actually use. Titles, headers, and meta descriptions send a direct signal about what a page is and where you operate; a confusing layout or a clunky enquiry process loses the customer even after they've found you. We review every page for both — fixing what's structurally holding it back and what's making it harder than it needs to be for someone to actually get in touch — and do the same for a handful of your live listings. For anything needing a bigger rework, we'll tell you exactly what to prioritise next. Depending on what you'd prefer, we make these changes ourselves or advise you on exactly what to do.",
    "Content Audit":
      "We review your website's content — including a sample of live listings and any local market content you have — for what's outdated, missing, or simply no longer true. This matters for two reasons: search engines treat stale content less favourably, and inaccurate information quietly damages the trust a visitor places in your business. We fix or refresh what we can as part of this pass, and give you a clear list of what to update next and why.",
    "NAP Consistency Audit":
      "\"NAP\" stands for Name, Address, and Phone number — the core details that identify your business online. Consistency here directly affects your local search ranking: it's measured as a genuine ranking factor, and every mismatch quietly works against you. We check these match exactly everywhere your business appears — your website, Google, Bing, Apple, Companies House, Facebook, LinkedIn, your listings on Rightmove, Zoopla and OnTheMarket, industry bodies like Propertymark and RICS, review sites, and local directories — correcting every mismatch we find. Depending on what you'd prefer, we either fix it ourselves directly or hand you clear instructions for getting it corrected, along with guidance on keeping it consistent going forward.",
    "Profile Setup Audit":
      "For most local searches, your business profile is the very first impression a potential customer gets — often before they've even visited your website. This directly affects your SEO: profile completeness and accuracy across Google, Bing, and Apple is measured as one of the biggest factors in local search ranking, and an incomplete or poorly set up profile quietly holds your ranking back regardless of how good your website is. We review and properly set up your presence on Google Business Profile, Bing Places, and Apple Business Connect — including Apple, one of the easiest, least competitive opportunities available right now since most property businesses haven't claimed theirs at all. Depending on what you'd prefer, we set everything up ourselves or hand you clear instructions to do it yourself, along with guidance on exactly what to keep updated going forward to keep each profile working in your favour.",
    "Profile Activity":
      "Google and Apple both reward business profiles that look genuinely active, and quietly downrank ones that look abandoned — activity and freshness are a measured part of how these platforms decide your local visibility, so an active profile directly improves your SEO. We build you an automated system that posts quick updates to your profiles on its own — a new instruction, a seasonal message — so your profiles stay visibly active with zero effort required from you. We'll talk you through what's being posted, so you always know what's going out in your name.",
    "Total Visibility Audit":
      "This is one of our biggest unique factors. Most agencies only ever ask \"how's your Google profile looking?\" — this audit asks a bigger question: are you actually present, at all, everywhere a customer might look for you? In the UK, Safari alone accounts for roughly 30% of all web traffic, and over half of UK mobile browsing happens on it — yet plenty of businesses have never checked whether they show up properly there at all. Beyond Google, Bing, and Apple, we check your presence across the platforms most businesses forget entirely — WhatsApp Business, voice assistant discovery, and any property-industry-specific channels relevant to you. Depending on what you'd prefer, we set up and claim what's missing ourselves, or hand you a clear, prioritised plan for closing the gaps yourself — either way, you get a single strategic view of where you exist, where you're invisible, and what matters most to fix first.",
    "SEO & ROI Reporting":
      "SEO results build gradually and shift month to month as search engines, competitors, and your own website all keep moving — a single snapshot can't show you that story. Every month, we translate what's actually happening into a clear, plain-English update — no jargon, no vanity metrics — so you always know exactly where things stand and what's genuinely moving the needle. Alongside that, we show you what it's actually worth: in real terms, what your organic visibility is worth compared to what you'd otherwise be paying per lead through a property portal — making the value of this work tangible and current, not just theoretical.",
  },
  geo: {
    "AI Crawler Access Check":
      "Around 1 in 4 business websites accidentally block the very crawlers that power AI citations, usually through security settings that treat ChatGPT's or Perplexity's crawler the same as a malicious bot. OpenAI states plainly that a blocked site will never appear in ChatGPT's search answers — not ranked lower, genuinely invisible. We check whether your site is silently blocking any major AI crawler, and fix it.",
    "Answer-Ready Content Audit & Fix":
      "Pages built around clear, specific facts and figures are roughly 40% more likely to get quoted by an AI tool than vague, general text. AI doesn't browse your website like a person does — it scans for a direct answer to a specific question and lifts it straight into its response. This is about the content you already have. Depending on what you'd prefer, we rewrite your key pages ourselves as part of Foundation, or give you a clear guide for structuring anything new you publish going forward.",
    "Freshness Audit & Fix":
      "Content that AI actually cites is roughly a quarter more recently updated, on average, than content that simply ranks well on Google — and half of it was refreshed within the last three months. AI models quietly stop citing pages that haven't been touched in a while, even ones that ranked well before. Depending on what you'd prefer, we refresh your most important pages ourselves as part of Foundation, or leave you with a clear plan for keeping the rest current yourself.",
    "AI Trust Signals":
      "Google, Microsoft, and OpenAI have all confirmed they use this kind of structured data to help decide what to say about a business. Beyond what a human reads, AI relies on a hidden layer of code — including a dedicated llm.txt file, written specifically for AI crawlers — to understand exactly what your business is, what it does, and where. Without it, AI is working from guesswork rather than fact. We build this directly into your website on Foundation.",
    "Review & Rating Schema":
      "There's a specific type of code called \"AggregateRating schema\" that lets a website declare its review score and count in a format machines read as verified fact — the same mechanism behind the star ratings you sometimes see directly in search results. For \"best X\" and comparison-style questions, AI increasingly uses this declared number as a direct filter when building its shortlist, rather than reading a page and estimating your reputation from the words on it. We take the genuine review score and count already being built through your Review Management, and add this code to your site correctly — including the required attribution back to where the reviews actually came from, since AI and search engines discount ratings that look self-published.",
    "AI Visibility Audit & Fix":
      "Only 11% of businesses cited by one AI tool are also cited by another — 89% of citations are platform-exclusive. We test the exact real-world questions your customers ask — \"best estate agent in [town]\" — across ChatGPT, Google's Gemini-powered AI Overviews, Microsoft's Copilot, and Apple's Siri. Depending on what you'd prefer, we fix what we can put right immediately ourselves, or give you a clear, practical guide for closing the gaps yourself.",
    "AI Query Mapping":
      "The Visibility Audit and Answer-Ready Content both work with questions and pages you already know about. This is different: it's about finding the real questions your future customers are asking that you currently have nothing written on at all. Real buyers and sellers ask AI dozens of things beyond the obvious — \"is now a good time to sell in [town],\" \"what's the average time on market,\" \"how much is stamp duty on a second home\" — and what people ask shifts with the market. We research this every month and build genuinely new content around the gaps we find, rather than just polishing what already exists.",
    "Knowledge Panel & Entity Optimisation":
      "Being mentioned by name across the web is now a stronger predictor of AI visibility than traditional backlinks. Trust Signals give AI the raw data to read you correctly — this goes a step further, actively building your recognition as a distinct, established entity. Where a Google Knowledge Panel exists or is eligible for your business, we claim and correct it; either way, we keep you consistently represented across Bing Places, Apple Business Connect, Companies House, and LinkedIn as those sources change over time, so every AI system stays confident you're one real business.",
    "Community & Forum Visibility":
      "Roughly 77% of what AI cites about a specific business comes from somewhere other than that business's own website — often a forum or community discussion. Your own site can only ever cover a minority of what AI actually reads about you. We build a genuine, ongoing presence in the property discussions your future customers are already having — answering real questions in the right places, consistently, month after month.",
    "AI Reputation Response":
      "AI can get basic facts about your business wrong — the wrong opening hours, an outdated service list, even wrongly suggesting you've closed down — and there's no notification system that tells you when this happens, the way there is for a bad review. We check what each major AI platform is currently saying about your business on a regular cycle, and where something's inaccurate or damaging, we act on it quickly rather than leaving it for the next scheduled report.",
    "Full-Funnel Attribution":
      "Visibility on its own doesn't prove it's working — the same AI mention can mean nothing or mean a real sale, and there's no way to tell the difference without tracking it. We track AI-driven traffic where it's technically detectable, add simple \"how did you hear about us\" tracking to your enquiry process, and compare your AI visibility against real enquiry and instruction data each month.",
  },
  reviews: {
    "AI Review Responder":
      "89% of consumers say they're more likely to choose a business that responds to every review, yet only 54% of reviews get any response at all. We check every place a review could appear — Google, Bing, Trustpilot, Facebook, and Yelp and Tripadvisor specifically, since Apple Business Connect quietly pulls its reviews from those two. We start by clearing your entire existing backlog, then an AI responder handles every new one as it comes in, drafting a genuine, well-considered reply in your voice — with a light layer of human oversight built in, since consumers trust a business less when a response feels purely robotic with nobody checking it.",
    "Automatic Review Reminders":
      "74% of consumers specifically look for reviews written within the last three months — a business surviving on reviews from two years ago is quietly losing trust, regardless of its star rating. The best moment to ask is right after you've helped someone, which is exactly the moment it's easiest to forget. We build and run a system that automatically sends a request the instant a service completes — a sale finishing, a tenancy starting, a stay ending — with a gentle automatic follow-up if they don't respond the first time.",
    "Review Monitoring & Reporting":
      "Consistent review responses have been shown to lift average ratings by 0.3-0.7 stars within six months. Every month, we track your review count, average rating, and response speed across every platform — Google, Bing, Apple, Trustpilot, and Facebook — and show you exactly how you're trending.",
    "Sentiment & Theme Analysis":
      "87% of unhappy customers contact a business directly before ever posting a negative review — meaning by the time a pattern shows up publicly, it's often already happened privately several times first. Each month, we identify the genuine patterns across everything customers are saying, good and bad, and flag anything recurring before it becomes a public problem.",
    "Reputation Crisis Response":
      "A negative review responded to within 4 hours is three times more likely to end in the reviewer actually updating their rating — but that window closes fast. This is different from the routine AI Responder above: a single review sitting unanswered is routine; a sudden cluster of negative reviews, or one severe enough to do real damage, isn't. We monitor for exactly that, with a human checking in directly on anything sensitive, and respond immediately rather than waiting for the next scheduled cycle.",
  },
  "market-intelligence": {
    "Competitor SEO & GEO Benchmarking":
      "A competitor gaining just 10 fresh reviews a month can outrank a business sitting on 200 reviews from three years ago — volume alone doesn't win, momentum does, and you can't see that without watching them too. Every month, we track your closest competitors across everything that matters — where they rank in Google, how visible they are in Bing and Apple, their review count and rating, how complete and active their business profiles are, and how often each of you is being named when someone asks ChatGPT or Gemini who to use. We put this side by side with your own numbers, so instead of a vague sense of \"we should be doing better,\" you get a precise, month-by-month picture of exactly where you're ahead, where you're being outpaced, and by how much.",
    "Search & AI Trend Updates":
      "56% of local businesses still haven't adjusted anything for AI-driven search at all — which means most of your competitors are already behind on the exact shifts we're watching for you. What people are actually searching for — on Google, and increasingly by asking AI tools like ChatGPT, Gemini, and Copilot directly — shifts constantly, and most of it happens invisibly to a business owner who's busy running the day-to-day. A change in interest rates, a new piece of tenancy legislation, a seasonal spike in demand for a particular property type or area — all of it changes what your future customers are asking, often weeks before it shows up in your enquiries. Every month, we keep watch on this and flag what's genuinely rising in relevance to your specific business and local market, so you're finding out about a shift while there's still time to act on it.",
  },
  scale: {
    "Replicable by Design":
      "Most multi-location businesses hit a wall because every new site depends on manual effort starting over. Every schema template, every trust signal, every content system built for your first branch was designed from day one to be duplicated — so a brand-new location gets SEO, GEO, reviews, and market intelligence live together from opening day, not staggered in over the months your original branch took to build.",
    "Brand Authority Inheritance":
      "Separately from the templates themselves, there's a structural decision that matters just as much: a new branch page built as part of your existing website, rather than a standalone site of its own, inherits some of the trust your main domain has already earned. This is why a 50th branch can rank faster than your 1st one ever did — it's a one-time architectural choice, not something that gets redone per branch.",
    "Consistency at Scale":
      "As branch count grows, so does the number of places your name, address, and phone number can quietly drift out of sync, and even a small inconsistency rate compounds fast: a fifth of your locations can end up actively undermining the other four-fifths. We monitor every branch, every platform, continuously — checking new locations as they open and re-checking existing ones as their details change.",
    "Group-Level & Branch-Level Reporting":
      "A regional director scanning fifty branches needs something completely different from a single office manager checking their own patch. The branch-level report is short and specific: that location's own rankings, reviews, and AI visibility, month over month. The group-level report is a full network comparison instead — every branch side by side, showing which are pulling ahead, which are falling behind, and where head office should focus attention next.",
    "White-Label Option":
      "Every report and dashboard above can carry your own branding instead of ours — your logo, your name, your colours. For franchise groups rolling this out to franchisees, it appears as an in-house service belonging to you, not a third-party vendor those franchisees have never heard of. The work itself doesn't change; only whose name is on it does.",
    "Territory Exclusivity":
      "We work with only one estate agency per local area, full stop. For an independent agent, the advantage you're paying for can never be bought by the rival down the road. For a chain, every new territory you expand into gets locked in the moment you do — a competitor opening in that same town after you can never access Reyse there at all.",
  },
};

export const archivedAddOnDescriptions: Record<string, Record<string, string>> = {
  seo: {
    "Video/YouTube SEO Audit":
      "YouTube is the world's second most-visited website, and property is one of the most natural fits for video — walkthroughs, \"moving to the area\" guides, agent introductions. But most agencies publishing video get almost no SEO value from it, because the video itself is never actually set up to be found. We review your existing video content and check whether the titles, descriptions, and tags are properly written around what people actually search for, whether the video is linked correctly back to your website and relevant listings, and whether it's using the kind of thumbnails and structure that get clicked on rather than scrolled past. Depending on what you'd prefer, we implement these fixes directly or hand you a clear report so your own team can action it. The result: instead of views quietly happening in isolation, your video content starts working alongside the rest of your SEO — driving genuine traffic and enquiries, not just watch time.",
    "Conversion Tracking Setup":
      "Everything else in this offer is designed to get more of the right people to your website and profiles — but without proper tracking, it's genuinely difficult to know which specific piece of work is actually driving real phone calls and enquiries versus just traffic. We set up dedicated tracking numbers and tools that record exactly which page, listing, or platform a genuine enquiry came from — so if a call comes in, you can see it was generated by, say, your Google Business Profile rather than your Bing listing, or a specific area guide page rather than your homepage. Over time, this builds a clear, evidence-based picture of exactly what's working best for your business specifically, so future effort and any additional budget can be focused precisely where it delivers the strongest return, rather than spread evenly across everything on a guess.",
  },
};
